cc_library(
  name = "ix",
  srcs = ["ix.cc"],
  hdrs = ["ix.h"],
  deps = [
    "//:global",
    "//:return_code",
    "//filesystem:filesystem",
    "//recordmanager:rm_rid",
  ],
  visibility = ["//visibility:public"],
)