#ifndef RETURN_CODE_H
#define RETURN_CODE_H

#define NO_ERROR 0

#define RM_ERROR 101
#define RM_RID_NOT_INITIALIZED_ERROR 102
#define RM_RID_MULTIPLE_SET_ERROR 103
#define RM_RECORD_NOT_INITIALIZED_ERROR 104
#define RM_RECORD_INVALID_LENGTH_ERROR 105
#define RM_RECORD_MULTIPLE_SET_ERROR 106

#endif  // RETURN_CODE_H