#ifndef RETURN_CODE_H
#define RETURN_CODE_H

#define NO_ERROR 0

#define UTILS_BITMAP_POSITION_OUT_OF_BOUNDS_ERROR 1

#define RM_ERROR 101
#define RM_RID_NOT_INITIALIZED_ERROR 102
#define RM_RID_MULTIPLE_SET_ERROR 103
#define RM_RECORD_NOT_INITIALIZED_ERROR 104
#define RM_RECORD_INVALID_LENGTH_ERROR 105
#define RM_RECORD_MULTIPLE_SET_ERROR 106
#define RM_FILEHANDLE_RECORD_NOT_FOUND_ERROR 107
#define RM_MANAGER_DUPLICATE_FILE_NAME_ERROR 108
#define RM_MANAGER_FILE_NOT_FOUND_ERROR 109

#endif  // RETURN_CODE_H