cc_library(
  name = "sm",
  srcs = ["sm.cc"],
  hdrs = ["sm.h"],
  deps = [
    "//:global",
    "//filesystem:filesystem",
    "//recordmanager:rm",
    "//indexing:ix",
  ],
  visibility = ["//visibility:public"],
)


